name: 'App Center CLI with Outputs Node 18'
description: 'GitHub Action to use any App Center CLI command'
author: 'Joris Abalea'
inputs: 
  command:
    description: 'The full App Center CLI command'
    required: true 
  token:
    description: 'Upload token - you can get one from appcenter.ms/settings'
    required: true 
outputs:
  out: # id of output
    description: 'App center cli output'
branding:
  color: 'red' 
  icon: 'send'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.token }}

